# Nixpacks configuration for Railway deployment
# This file is used by Railway to build and run the application

[phases.setup]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[phases.install]
cmds = [
  "npm install --production"
]

[start]
# Use the start.sh script which handles dependency installation
cmd = "sh start.sh"

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"  # Ensures devDependencies are installed during build
PORT = "3001"
NPM_CONFIG_PRODUCTION = "false"

[build.args]
NODE_VERSION = "18"

[build.nodejs]
install_scripts = true
install_dev_deps = true
